default: &default
  adapter: postgres
  encoding: utf8
  username: user
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  host: db
  password: password

test:
  <<: *default
  database: app_test
  host: db
  password: password

# production:
#   <<: *default
#   database: app_production
#   username: app
#   password: <%= ENV["APP_DATABASE_PASSWORD"] %>
